### ISSUE TITLE
rosmake does not properly send pthread flags for sicktoolbox_wrapper

### ISSUE THREAD

**Issue by chadrockey** [ros/catkin#257] opened 2012-11-14 23:45 UTC
For sicktoolbox_wrapper revision 40260:
https://code.ros.org/svn/ros-pkg/stacks/laser_drivers/trunk

https://code.ros.org/gf/project/ros-pkg/scmsvn/?action=browse&path=%2Fstacks%2Flaser_drivers%2F

There is an interaction between Ubuntu's use of the linker flag '--as-needed' and the ordering of the flags from rosmake and the manifest.

 rosmake --pre-clean sicktoolbox_wrapper 
[ rosmake ] rosmake starting...  
[ rosmake ] Packages requested are: ['sicktoolbox_wrapper']  
[ rosmake ] Logging to directory /u/chadrockey/.ros/rosmake/rosmake_output-20121114-165845  
[ rosmake ] Expanded args ['sicktoolbox_wrapper'] to:
['sicktoolbox_wrapper']  
[rosmake-0] Starting >>> sicktoolbox [ make clean ]  
[rosmake-1] Starting >>> roscpp [ make clean ]  
[rosmake-2] Starting >>> sensor_msgs [ make clean ]  
[rosmake-1] Finished <<< roscpp  No Makefile in package roscpp  
[rosmake-3] Starting >>> diagnostic_updater [ make clean ]  
[rosmake-1] Starting >>> sicktoolbox_wrapper [ make clean ]  
[rosmake-2] Finished <<< sensor_msgs  No Makefile in package sensor_msgs  
[rosmake-3] Finished <<< diagnostic_updater  No Makefile in package diagnostic_updater  
[rosmake-0] Finished <<< sicktoolbox [PASS] [ 0.04 seconds ]  
[rosmake-1] Finished <<< sicktoolbox_wrapper [PASS] [ 0.28 seconds ]  
[rosmake-0] Starting >>> sicktoolbox [ make ]  
[rosmake-1] Starting >>> roscpp [ make ]  
[rosmake-2] Starting >>> sensor_msgs [ make ]  
[rosmake-3] Starting >>> diagnostic_updater [ make ]  
[rosmake-2] Finished <<< sensor_msgs  No Makefile in package sensor_msgs  
[rosmake-1] Finished <<< roscpp  No Makefile in package roscpp  
[rosmake-3] Finished <<< diagnostic_updater  No Makefile in package diagnostic_updater  
[rosmake-0] Finished <<< sicktoolbox [PASS] [ 12.58 seconds ]  
[rosmake-0] Starting >>> sicktoolbox_wrapper [ make ]  
[ rosmake ] Last 40 linescktoolbox_wrapper: 17.0 sec ]                                                                                                                                                                                             [ 1 Active 4/5 Complete ]
{-------------------------------------------------------------------------------
  -- Looking for include files CMAKE_HAVE_PTHREAD_H - found
  -- Looking for pthread_create in pthreads
  -- Looking for pthread_create in pthreads - not found
  -- Looking for pthread_create in pthread
  -- Looking for pthread_create in pthread - found
  -- Found Threads: TRUE 
  -- Found gtest sources under '/usr/src/gtest': gtests will be built
  -- catkin 0.5.51
  [rosbuild] Including /opt/ros/groovy/share/roscpp/rosbuild/roscpp.cmake
  [rosbuild] Including /opt/ros/groovy/share/rospy/rosbuild/rospy.cmake
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /u/chadrockey/release/laser_drivers/sicktoolbox_wrapper/build
  cd build && make -j -l8
  make[1]: Entering directory `/wg/stor5/chadrockey/release/laser_drivers/sicktoolbox_wrapper/build'
  make[2]: Entering directory`/wg/stor5/chadrockey/release/laser_drivers/sicktoolbox_wrapper/build'
  make[3]: Entering directory `/wg/stor5/chadrockey/release/laser_drivers/sicktoolbox_wrapper/build'
  Scanning dependencies of target rospack_genmsg_libexe
  make[3]: Leaving directory`/wg/stor5/chadrockey/release/laser_drivers/sicktoolbox_wrapper/build'
  [  0%] Built target rospack_genmsg_libexe
  make[3]: Entering directory `/wg/stor5/chadrockey/release/laser_drivers/sicktoolbox_wrapper/build'
  Scanning dependencies of target rosbuild_precompile
  make[3]: Leaving directory`/wg/stor5/chadrockey/release/laser_drivers/sicktoolbox_wrapper/build'
  [  0%] Built target rosbuild_precompile
  make[3]: Entering directory `/wg/stor5/chadrockey/release/laser_drivers/sicktoolbox_wrapper/build'
  Scanning dependencies of target print_scans
  make[3]: Leaving directory`/wg/stor5/chadrockey/release/laser_drivers/sicktoolbox_wrapper/build'
  make[3]: Entering directory `/wg/stor5/chadrockey/release/laser_drivers/sicktoolbox_wrapper/build'
  [100%] Building CXX object standalone/CMakeFiles/print_scans.dir/print_scans.cpp.o
  Linking CXX executable ../../bin/print_scans
  /u/chadrockey/release/laser_drivers/sicktoolbox/sicktoolbox/lib/libsicklms-1.0.so: undefined reference to`pthread_create'
  /u/chadrockey/release/laser_drivers/sicktoolbox/sicktoolbox/lib/libsicklms-1.0.so: undefined reference to `pthread_join'
  collect2: ld returned 1 exit status
  make[3]: *** [../bin/print_scans] Error 1
  make[3]: Leaving directory`/wg/stor5/chadrockey/release/laser_drivers/sicktoolbox_wrapper/build'
  make[2]: **\* [standalone/CMakeFiles/print_scans.dir/all] Error 2
  make[2]: Leaving directory `/wg/stor5/chadrockey/release/laser_drivers/sicktoolbox_wrapper/build'
  make[1]: *** [all] Error 2
  make[1]: Leaving directory`/wg/stor5/chadrockey/release/laser_drivers/sicktoolbox_wrapper/build'

The difference between the Fuerte and Groovy when running 'VERBOSE=1 make":
Fuerte:
/usr/bin/c++   -O2 -g    -Wl,-rpath,/u/chadrockey/release/laser_drivers/sicktoolbox/sicktoolbox/lib -pthread CMakeFiles/print_scans.dir/print_scans.o  -o ../../bin/print_scans -rdynamic -L/u/chadrockey/release/laser_drivers/sicktoolbox/sicktoolbox/lib -L/opt/ros/fuerte/lib -lsicklms-1.0 -lpthread -lroscpp -lrostime -lrosconsole -lroscpp_serialization -lxmlrpcpp -Wl,-rpath,/u/chadrockey/release/laser_drivers/sicktoolbox/sicktoolbox/lib:/opt/ros/fuerte/lib 

Groovy:
/usr/bin/c++   -O2 -g    -Wl,-rpath,/u/chadrockey/release/laser_drivers/sicktoolbox/sicktoolbox/lib -pthread CMakeFiles/print_scans.dir/print_scans.cpp.o  -o ../../bin/print_scans -rdynamic -L/u/chadrockey/release/laser_drivers/sicktoolbox/sicktoolbox/lib -L/opt/ros/groovy/lib -lsicklms-1.0 -lroscpp -lboost_signals-mt -lboost_filesystem-mt -lrosconsole -lroscpp_serialization -lxmlrpcpp -lrostime -lboost_date_time-mt -lboost_system-mt -lboost_thread-mt -lpthread -lcpp_common -Wl,-rpath,/u/chadrockey/release/laser_drivers/sicktoolbox/sicktoolbox/lib:/opt/ros/groovy/lib

**Comment by dirk-thomas** [comment] 2012-11-15 00:32
According to the above error message you are mixing Fuerte and Groovy.

While these lines:

`Using CATKIN_DEVEL_PREFIX`
`Using CMAKE_PREFIX_PATH: /opt/ros/groovy`

Indicate that you are running Groovy the next message:

`/opt/ros/fuerte/share/ros/core/rosbuild/rostoolchain.cmake`

is looking for the dry rosbuild under Fuerte.

Please wipe your build folders and retry from a clean environment.

Reopen the ticket if the problem is still there or post a detailed list of commands you ran which lead to this weird state.

**Comment by chadrockey** [comment] 2012-11-15 01:02
That was human error, I pasted from the wrong terminal.  I've updated the ticket, but cannot reopen.

**Comment by chadrockey** [comment] 2012-11-16 01:36
Workaround for issue:
https://code.ros.org/gf/project/ros-pkg/scmsvn/?action=ScmCommitDetail&scm_commit_id=140514

I'm not sure if this is a catkin or sicktoolbox issue.  It seems very picky on the order of the flags.

**Comment by dirk-thomas** [comment] 2013-01-24 21:13
There have been changes recently to avoid link flag ordering but I am not sure if they apply for the described issue.
@chadrockey: Please retry with the current packages (from shadow-fixed) and without the workaround in laser_drivers and report back if the issue is still valid.

**Comment by chadrockey** [comment] 2013-01-24 22:04
Looks like the workaround is still required, I reverted these two commits and got the following output:
https://github.com/ros-drivers/sicktoolbox/commit/3155eecdff9ad614876f73106dca97dec4443eb9
https://github.com/ros-drivers/sicktoolbox_wrapper/commit/178cebd55c3ee7c9af2bc443c8584a74fd8d3c98
  /u/chadrockey/platformbot/sicktoolbox/sicktoolbox/lib/libsicklms-1.0.so: undefined reference to `pthread_create'
  /u/chadrockey/platformbot/sicktoolbox/sicktoolbox/lib/libsicklms-1.0.so: undefined reference to`pthread_join'

**Comment by dirk-thomas** [comment] 2013-02-04 21:26
Duplicate of ros/ros_comm#135

**Closed as completed by dirk-thomas** 2013-02-04 21:26 UTC
Labels: duplicate
