### ISSUE TITLE
Switching workspaces pollutes LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by miguelprada** [ros/catkin#809] opened 2016-06-17 08:52 UTC
I just realised that when switching workspaces, i.e. sourcing a `setup.bash` from a new develspace, the path to the `lib` folder in the previously sourced workspace is still present in LD_LIBRARY_PATH.

Is this intended? Am I wrong in supposing that sourcing a new `setup.bash` should clean-up whatever ROS setup was done by a previous setup? Is there a recommended way to cleanly switch to a new workspace after already having sourced a different workspace setup file?

**Comment by dirk-thomas** [comment] 2016-06-17 15:25
I have a clean workspace (built with nothing sourced before) as well as the installed packages in `/opt/ros/kinetic`. When I source one of them and afterwards the other the `LD_LIBRARY_PATH` does not get polluted by is being reset to only contain the lib folder of the sourced prefix. 

Can you please provide a sequence of commands to reproduce the problem?

**Comment by miguelprada** [comment] 2016-06-20 07:02
See the sequence below:

``` bash
user@host:~$ env | grep ros
user@host:~$ env | grep ROS
user@host:~$ source /opt/ros/indigo/setup.bash 
user@host:~$ mkdir -p /tmp/ws1/src
user@host:~$ cd /tmp/ws1/src/
user@host:/tmp/ws1/src$ catkin_init_workspace 
Creating symlink "/tmp/ws1/src/CMakeLists.txt" pointing to "/opt/ros/indigo/share/catkin/cmake/toplevel.cmake"
user@host:/tmp/ws1/src$ cd ..
user@host:/tmp/ws1$ catkin_make
Base path: /tmp/ws1
Source space: /tmp/ws1/src
Build space: /tmp/ws1/build
Devel space: /tmp/ws1/devel
Install space: /tmp/ws1/install
...
-- Using CATKIN_DEVEL_PREFIX: /tmp/ws1/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/indigo
-- This workspace overlays: /opt/ros/indigo
...
user@host:/tmp/ws1$ mkdir -p /tmp/ws2/src
user@host:/tmp/ws1$ cd /tmp/ws2/src/
user@host:/tmp/ws2/src$ catkin_init_workspace 
Creating symlink "/tmp/ws2/src/CMakeLists.txt" pointing to "/opt/ros/indigo/share/catkin/cmake/toplevel.cmake"
user@host:/tmp/ws2/src$ cd ..
user@host:/tmp/ws2$ catkin_make
Base path: /tmp/ws2
Source space: /tmp/ws2/src
Build space: /tmp/ws2/build
Devel space: /tmp/ws2/devel
Install space: /tmp/ws2/install
...
-- Using CATKIN_DEVEL_PREFIX: /tmp/ws2/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/indigo
-- This workspace overlays: /opt/ros/indigo
...
user@host:/tmp/ws2$ cd ..
user@host:/tmp$ source ws1/devel/setup.bash 
user@host:/tmp$ env | grep ros
RTT_COMPONENT_PATH=/tmp/ws1/devel/lib/orocos:/opt/ros/indigo/lib/orocos
ROS_ROOT=/opt/ros/indigo/share/ros
ROS_PACKAGE_PATH=/tmp/ws1/src:/opt/ros/indigo/share:/opt/ros/indigo/stacks
LD_LIBRARY_PATH=/tmp/ws1/devel/lib:/opt/ros/indigo/lib/x86_64-linux-gnu:/opt/ros/indigo/lib
CPATH=/opt/ros/indigo/include
PATH=/opt/ros/indigo/bin:/home/user/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
LUA_PATH=;;/opt/ros/indigo/share/lua/5.1/?.lua;/opt/ros/indigo/share/lua/5.1/rfsm/?.lua;/opt/ros/indigo/share/lua/5.1/?.lua;/opt/ros/indigo/share/lua/5.1/rfsm/?.lua
LUA_CPATH=;;/opt/ros/indigo/lib/lua/5.1/?.so;/opt/ros/indigo/lib/lua/5.1/?.so
PYTHONPATH=/opt/ros/indigo/lib/python2.7/dist-packages
PKG_CONFIG_PATH=/opt/ros/indigo/lib/x86_64-linux-gnu/pkgconfig:/opt/ros/indigo/lib/pkgconfig
CMAKE_PREFIX_PATH=/tmp/ws1/devel:/opt/ros/indigo
ROS_ETC_DIR=/opt/ros/indigo/etc/ros
user@host:/tmp$ source ws2/devel/setup.bash 
user@host:/tmp$ env | grep ros
RTT_COMPONENT_PATH=/tmp/ws2/devel/lib/orocos:/opt/ros/indigo/lib/orocos
ROS_ROOT=/opt/ros/indigo/share/ros
ROS_PACKAGE_PATH=/tmp/ws2/src:/opt/ros/indigo/share:/opt/ros/indigo/stacks
LD_LIBRARY_PATH=/tmp/ws2/devel/lib:/opt/ros/indigo/lib/x86_64-linux-gnu:/tmp/ws1/devel/lib:/opt/ros/indigo/lib
CPATH=/opt/ros/indigo/include
PATH=/opt/ros/indigo/bin:/home/user/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
LUA_PATH=;;/opt/ros/indigo/share/lua/5.1/?.lua;/opt/ros/indigo/share/lua/5.1/rfsm/?.lua;/opt/ros/indigo/share/lua/5.1/?.lua;/opt/ros/indigo/share/lua/5.1/rfsm/?.lua;/opt/ros/indigo/share/lua/5.1/?.lua;/opt/ros/indigo/share/lua/5.1/rfsm/?.lua
LUA_CPATH=;;/opt/ros/indigo/lib/lua/5.1/?.so;/opt/ros/indigo/lib/lua/5.1/?.so;/opt/ros/indigo/lib/lua/5.1/?.so
PYTHONPATH=/opt/ros/indigo/lib/python2.7/dist-packages
PKG_CONFIG_PATH=/opt/ros/indigo/lib/x86_64-linux-gnu/pkgconfig:/opt/ros/indigo/lib/pkgconfig
CMAKE_PREFIX_PATH=/tmp/ws2/devel:/opt/ros/indigo
ROS_ETC_DIR=/opt/ros/indigo/etc/ros
user@host:/tmp$ 
```

Note how, after sourcing `/tmp/ws2/devel/setup.bash`, the `LD_LIBRARY_PATH` environment variable still contains traces of `ws1`.

Moreover, the path to `ws1` appears **before** `/opt/ros/indigo/lib`. If `ws1` contained sources of binary packages in `/opt/ros/...`, then the libs generated in `ws1` develspace would hide the ones in `/opt` after sourcing `ws2`. This was unexpected to me, although maybe it's intentional.

**Comment by dirk-thomas** [comment] 2016-06-20 15:18
I tried the above sequence with Kinetic and got the expected results. After sourcing the first:

```
LD_LIBRARY_PATH=/tmp/ws1/devel/lib:/opt/ros/kinetic/lib
```

and after the second:

```
LD_LIBRARY_PATH=/tmp/ws2/devel/lib:/opt/ros/kinetic/lib
```

Can you please provide more information, e.g. the version of `catkin` you are using.

**Comment by miguelprada** [comment] 2016-06-21 09:12
I'm using Indigo. Is this no longer an issue then? And, is there a suggested way of doing this in Indigo?

**Comment by dirk-thomas** [comment] 2016-06-21 13:55
I am not aware of a fix which is only available on Kinetic but not on Indigo.

Can you please post the version number of catkin you are using.

**Comment by miguelprada** [comment] 2016-06-22 07:55
I'm using the version released as ros-indigo-catkin for trusty, i.e. 0.6.18.

**Comment by dirk-thomas** [comment] 2016-06-24 22:13
I tried the same in a clean Docker container using Indigo on Trusty and it still behaves correctly for me. Since the workspace is empty it might be related to what packages you have installed.

I assume you have an up-to-date system (`sudo apt update && sudo apt dist-upgrade`).

Please try it on a different machine / virtual machine / Docker container with just `ros-indigo-ros-core` being installed. If that works than maybe try to install all the same packages as on your machine and check if that changes anything.

**Comment by miguelprada** [comment] 2016-06-28 15:00
Ok, it obviously doesn't happen to me either on a clean indigo docker image. :sweat:

I'm baffled about this, and not quite sure how to troubleshoot my system to find out what's causing this issue. I'll give it a try and let you know if I find anything.

Thanks for your help, anyways, @dirk-thomas!

**Comment by dirk-thomas** [comment] 2016-06-28 15:03
I will close this ticket for now. If you find anything please comment with more information here and it can be reopened.

**Comment by miguelprada** [comment] 2016-06-28 15:52
I noticed the missing `/opt/ros/indigo/lib/x86_64-linux-gnu` in the clean indigo environment's `LD_LIBRARY_PATH`, when compared to mine.

After a bit of grep magic, I found out that it seems somehow related to `moveit_planners_ompl` package, and after installing `ros-indigo-moveit-planners-ompl` (and its dependencies, of course) in the clean docker image, I start getting the results shown in my initial post.

Any idea about how this interaction can happen?

**Comment by dirk-thomas** [comment] 2016-06-28 15:58
I don't see anything special in `moveit_planners_ompl` itself. But it has a lot of recursive dependencies. Can you please try to narrow it down to which of the dependencies introduces the problem.

**Comment by miguelprada** [comment] 2016-06-29 09:04
After checking the dependencies of `moveit_planners_ompl`, it seems that the issue is introduced by `ompl` package itself (installed via `ros-indigo-ompl`).

Maybe an issue should be opened in the [`ompl` repo](https://bitbucket.org/ompl/ompl/)? What do you think @dirk-thomas?

**Comment by dirk-thomas** [comment] 2016-06-29 21:00
I don't see on a first look what the package is doing. But if the problem only happens when `ompl` is installed then filling a ticket in their repo seems like the best way to go.

**Comment by dirk-thomas** [comment] 2016-08-04 15:27
@dornhege FYI

**Comment by dirk-thomas** [comment] 2016-08-04 15:35
After looking at this problem again I don't think it is a problem in `ompl`. But with `ompl` installed the `LD_LIBRARY_PATH` contains more than one path contributed by a ROS workspace. And the rollback logic doesn't correctly undo both entries but only one of them. So `ompl` with its uncommon lib path exposes a bug in the rollback logic.

I created PR #819. It would be great if you could both apply the changes to your `/opt/ros/<DISTRO>/_setup_util.py` file, try again, and report back if it fixes the problem for you.

**Comment by miguelprada** [comment] 2016-08-04 20:12
I just tried your changes but didn't seem to fix the problem for me.

Since I'm not quite sure whether I did it right, and just to be clear, what I did exactly was:
- Manually merge the changes from the `_setup_util.py.in` template in your PR to my `/opt/ros/indigo/_setup_util.py`
- Remove the automatic environment sourcing from `.bashrc`
- Open a new terminal and make sure no ROS stuff is in the environment
- Run [test_env_issues.bash](https://gist.github.com/miguelprada/bd6ab19d80cede90376353b042f7dbe2)

Did I do something wrong or is there any better way to test this? I'm not quite comfortable with the ROS, `catkin`, `setup.bash`, etc. plumbing.

**Comment by dirk-thomas** [comment] 2016-08-04 20:21
@miguelprada I just ran `test_env_issues.bash` locally (with Kinetic) and with the patch it returned "fine". Can you please share the content of your modified `_setup_util.py`.

**Comment by miguelprada** [comment] 2016-08-04 20:26
Sure @dirk-thomas, [here](https://gist.github.com/miguelprada/aec1fd728fca5e55b7b43e9c515b4a00).

**Comment by dirk-thomas** [comment] 2016-08-04 20:40
I forgot to mention that you also need to update ~~`/opt/ros/<DISTRO>/share/catkin/cmake/templates/setup.sh.in`~~ `/opt/ros/<DISTRO>/share/catkin/cmake/templates/_setup_util.py.in`. This template is being used for the new workspace. Please let me know what the result is for you after that change.

**Comment by miguelprada** [comment] 2016-08-05 08:10
I'm not sure how I should change `setup.sh.in`, @dirk-thomas. There's no change to this file in #819, and the only difference between this file in `fix_rollback_logic` compared to the one in my `/opt/ros/indigo` folder is the removal of `export CPATH`.

I tried to modify this nevertheless, but it didn't affect the outcome of the test script in my machine.

**Comment by dirk-thomas** [comment] 2016-08-05 13:55
Sorry, I updated my previous comment. Of course it needs to be the modified `_setup_util.py.in` file.

Instead you could also clone `catkin` using the branch of the pull request into the two test workspaces.

**Comment by miguelprada** [comment] 2016-08-06 09:26
Ok @dirk-thomas, I still have no success by manually modifying the files in `/opt/ros/indigo`, but by [cloning catkin](https://gist.github.com/miguelprada/bd6ab19d80cede90376353b042f7dbe2) into the test workspaces I finally get a "fine" as well.

Thanks for your help!

**Comment by dirk-thomas** [comment] 2016-08-08 14:41
Thank you for the report, iterating with me, and trying the patch.

**Closed as completed by dirk-thomas** 2016-08-08 14:41 UTC
Labels: bug
