### ISSUE TITLE
Circular configure loop when changing the CMAKE_CXX_COMPILER option

### ISSUE THREAD

**Issue by wjwwood** [ros/catkin#121] opened 2012-04-12 18:05 UTC
To reproduce:
1. `rosinstall --catkin ~/ros-underlay http://ros.org/rosinstalls/fuerte-ros-full.rosinstall`
2. Add `set(CMAKE_CXX_COMPILER /usr/bin/llvm-g++)` to the top level CMakeLists.txt file right after `set(CMAKE_CXX_FLAGS_INIT "-Wall")`
3. `cd ~/ros-underlay`
4. `mkdir build`
5. `cd build`
6. `cmake .. -DCMAKE_INSTALL_PREFIX=/opt/ros/fuerte -DSETUPTOOLS_DEB_LAYOUT=OFF`

At this point you should get a circular configure loop that ends with this message before restarting the cmake configure loop:

```
...
-- Configuring done
You have changed variables that require your cache to be deleted.
Configure will be re-run and you may have to reset some variables.
The following variables have changed:
CMAKE_CXX_COMPILER= /usr/bin/c++

-- The C compiler identification is GNU
...
```

Is this intended behavior or is there a different, preferred method for changing cmake variables with catkin or is this a bug?

**Comment by gerkey** [comment] 2012-04-14 19:35
I can reproduce your result.

This is curious.  As @dirk-thomas pointed out, CMake seems to not want you to set the compiler from within CMake; regarding `CMAKE_C_COMPILER` (http://www.cmake.org/Wiki/CMake_Useful_Variables#Compilers_and_Tools):

```
Note! It can not be changed after the first cmake or ccmake run. Although the gui allows to enter an alternative, it will be ignored in the next 'configure' run. Use for example: 
CC=gcc-3.3 CXX=g++-3.3 cmake 
```

So I'm inclined to say "wontfix" because it's not a supported use case for CMake.  Instead of doing it from within code, you should set the compiler from outside CMake, and use a single compiler for all code within a single workspace.

But the catch is that setting the compiler from within code seems to work properly in rosconsole (https://code.ros.org/trac/ros/browser/stacks/ros_comm/trunk/tools/rosconsole/CMakeLists.txt).  I've verified on OSX that the conditional compiler-setting logic in that file is executed, and that the value of `CMAKE_CXX_COMPILER` indeed changes (in my case from `/usr/local/Cellar/ccache/3.1.6/libexec/c++` to `/usr/bin/g++-4.2`).

I don't understand why it works in `ros_comm/tools/rosconsole/CMakeLists.txt` but not in `CMakeLists.txt`.  I've tried changing the top-level assignment to use the value that works lower down (`/usr/bin/g++-4.2`), and I've tried moving the assignment to other non-top-level locations; in all cases I get the endless configure loop.

**Comment by wjwwood** [comment] 2012-04-15 22:01
Agreed, from the documentation I would say don't fix, but I have used this mechanism a lot of times to switch to clang without using command line ENV variables like they suggest.  I feel like I am missing some core concept of the cmake configure-generate cycle which makes this make sense...

**Comment by dirk-thomas** [comment] 2012-09-09 07:19
Please check if this is still relevant.

**Comment by wjwwood** [comment] 2012-09-16 01:45
This still happens.

**Comment by dirk-thomas** [comment] 2013-01-28 20:09
Closed as wontfix as this is not an allowed use case in CMake.

**Closed as completed by dirk-thomas** 2013-01-28 20:09 UTC
Labels: bug, wontfix
