### ISSUE TITLE
catkin_make hangs after -- BUILD_SHARED_LIBS is on

### ISSUE THREAD

**Issue by CarloKaram** [ros/catkin#1078] opened 2020-04-14 00:32 UTC
When creating a catkin workspace (empty or otherwise) and trying to catkin_make, the command hangs after displaying  -- BUILD_SHARED_LIBS is on without displaying any warning or error message. The last two lines of the command output are actually 
-- BUILD_SHARED_LIBS is on
-- BUILD_SHARED_LIBS is on

When I abort the process, the traceback displays the below as the most recent call (before KeyboardInterrupt)
 `File "/opt/ros/kinetic/lib/python2.7/dist-packages/catkin/builder.py", line 210, in run_command
    line = proc.stdout.readline()` 

It seems this line of code is causing some issues. I have already tried reinstalling ros and that didn't fix it. Is there anything I can do?

**Comment by dirk-thomas** [comment] 2020-04-14 03:28
Please provide reproduce steps, e.g. what exactly is in the workspace, what platform you use, etc.

**Comment by CarloKaram** [comment] 2020-04-14 12:04
I'm using Ubuntu 16.04 and ROS Kinetic.

Even creating an empty catkin workspace does not work, i.e:
`mkdir -p ~/catkin_ws/src`
`cd catkin_ws`
`source /opt/ros/kinetic/setup.bash`
`catkin_make`

**Comment by dirk-thomas** [comment] 2020-04-14 14:19
Closing due to cross posting; https://answers.ros.org/question/349360/catkin_make-hangs-after-build_shared_libs-is-on/

**Closed as completed by dirk-thomas** 2020-04-14 14:19 UTC
Labels: duplicate, question

**Comment by ninjapc90** [comment] 2020-05-08 19:22
I have insalled ROS melodic on Ubuntu 18.04. I abruptly  started facing the same issue. When I run `catkin_make` the system hangs on `BUILD_SHARED_LIBS is on`. This command was working perfectly earlier.  

Here is the console output - 

```
pooja:~/catkin_ws$ catkin_make
Base path: /home/pooja/catkin_ws
Source space: /home/pooja/catkin_ws/src
Build space: /home/pooja/catkin_ws/build
Devel space: /home/pooja/catkin_ws/devel
Install space: /home/pooja/catkin_ws/install
####
#### Running command: "cmake /home/pooja/catkin_ws/src -DCATKIN_DEVEL_PREFIX=/home/pooja/catkin_ws/devel -DCMAKE_INSTALL_PREFIX=/home/pooja/catkin_ws/install -G Unix Makefiles" in "/home/pooja/catkin_ws/build"
####
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using CATKIN_DEVEL_PREFIX: /home/pooja/catkin_ws/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/melodic
-- This workspace overlays: /opt/ros/melodic
-- Found PythonInterp: /usr/bin/python2 (found suitable version "2.7.17", minimum required is "2") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python2
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/pooja/catkin_ws/build/test_results
-- Found gtest sources under '/usr/src/googletest': gtests will be built
-- Found gmock sources under '/usr/src/googletest': gmock will be built
-- Found PythonInterp: /usr/bin/python2 (found version "2.7.17") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.7.23
-- BUILD_SHARED_LIBS is on
-- BUILD_SHARED_LIBS is on
```
On stopping the process following message is generated

```
^CTraceback (most recent call last):
  File "/opt/ros/melodic/bin/catkin_make", line 306, in <module>
    sys.exit(main())
  File "/opt/ros/melodic/bin/catkin_make", line 209, in main
    run_command_colorized(cmd, build_path)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/catkin/builder.py", line 189, in run_command_colorized
    run_command(cmd, cwd, quiet=quiet, colorize=True, add_env=add_env)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/catkin/builder.py", line 211, in run_command
    line = proc.stdout.readline()
KeyboardInterrupt
```

I list the packages with` rospack list-names`. All package names start with lower case. 
```

~/Desktop/catkin_ws/src$ echo $ROS_PACKAGE_PATH
/home/pooja/Desktop/catkin_ws/src:/opt/ros/melodic/share
```

**Comment by dirk-thomas** [comment] 2020-05-13 18:40
@poojacos Please do not cross post your question in multiple places (#1087).

**Comment by fylingcta** [comment] 2024-01-02 09:10
I also encountered the same problem, and using the top command, I can see that Python 3 occupies almost 100% of memory.The situation is the same as him, and before that, it can be compiled normally
![top](https://github.com/ros/catkin/assets/32047821/1c76a423-315a-4af4-85d8-d88b1f73b53e)
