### ISSUE TITLE
CATKIN_DEPENDS/find_package on *_msgs package does not add *_generate_messages_cpp target as dependency?

### ISSUE THREAD

**Issue by peci1** [ros/catkin#801] opened 2016-05-25 13:25 UTC
I have a pure message package `mesh_to_dae_msgs` (package.xml and CMakeLists included). Then I have a `mesh_to_dae` package which uses the messages defined in `mesh_to_dae_msgs` (catkin files also included).

I assumed that if I want to use the generated messages which are in a different package, then only `find_package(catkin REQUIRED COMPONENTS ... mesh_to_dae_msgs)` and `CATKIN_DEPENDS ... mesh_to_dae_msgs)` are needed (and specifying the package as build and run dependency in package.xml).

However, in my case, I'm not able to build the workspace this way. I always have to add `add_dependencies(mesh_to_dae mesh_to_dae_msgs_generate_messages_cpp)` to `mesh_to_dae/CMakeLists.txt`. Otherwise the message header files are not generated before `mesh_to_dae` is build. I think this should not be needed (because then usage of "core" ROS message packages would be different from usage of own message packages).

Ubuntu 14.04 64bit
ROS indigo
Using catkin_make. When I use catkin tools, it works (obviously, because of package isolation).

`mesh_to_dae_msgs/package.xml`:

```
<?xml version="1.0"?>
<package format="2">
  <name>mesh_to_dae_msgs</name>
  <version>2.0.0</version>
  <description>
      Message/service definitions for mesh_to_dae.
  </description>

  <maintainer email="martin.pecka@cvut.cz">Martin Pecka</maintainer>
  <license>TRADR</license>

  <buildtool_depend>catkin</buildtool_depend>

  <build_depend>message_generation</build_depend>
  <build_export_depend>message_runtime</build_export_depend>
  <exec_depend>message_runtime</exec_depend>

  <depend>std_msgs</depend>
</package>
```

`mesh_to_dae_msgs/CMakeLists.txt`:

```
cmake_minimum_required(VERSION 2.8.3)
project(mesh_to_dae_msgs)

find_package(catkin REQUIRED COMPONENTS
  message_generation
  std_msgs
)

add_service_files(
   FILES
   GetDae.srv
)

generate_messages(
   DEPENDENCIES
   std_msgs
)

catkin_package(
  CATKIN_DEPENDS message_runtime std_msgs
)
```

`mesh_to_dae/package.xml` (only interesting parts):

```
<?xml version="1.0"?>
<package format="2">
  <name>mesh_to_dae</name>
  <version>2.0.0</version>
  <description>Convert visualization_msgs/Marker::TRIANGLE_ARRAY to a DAE (Collada) file.</description>

  <maintainer email="peckama2@fel.cvut.cz">Martin Pecka</maintainer>
  <license>BSD</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>mesh_to_dae_msgs</depend>
  <depend>roscpp</depend>
</package>
```

`mesh_to_dae/CMakeLists.txt` (only interesting parts):

```
cmake_minimum_required(VERSION 2.8.3)
project(mesh_to_dae)

set(PROJECT_DEPS
  roscpp
  mesh_to_dae_msgs
)

find_package(catkin REQUIRED COMPONENTS ${PROJECT_DEPS})

catkin_package(
  INCLUDE_DIRS include
  LIBRARIES ${PROJECT_NAME}
  CATKIN_DEPENDS ${PROJECT_DEPS}
)

include_directories(include ${Boost_INCLUDE_DIRS} ${catkin_INCLUDE_DIRS})

add_executable(${PROJECT_NAME}_node src/mesh_to_dae_node.cpp)
target_link_libraries(${PROJECT_NAME}_node ${catkin_LIBRARIES})
```

**Comment by wjwwood** [comment] 2016-05-25 18:48
In the future, please ask questions like this on answers.ros.org (if you later determine there is a bug, then you should open an issue on GitHub). See: http://wiki.ros.org/Support

---

This is expected behavior. There is no way to "automatically" add the dependency. The behavior and the requirement to have this explicit dependency is documented here:

http://docs.ros.org/jade/api/catkin/html/howto/format2/cpp_msg_dependencies.html#cmakelists-txt

As well as here:

http://wiki.ros.org/catkin/CMakeLists.txt#Important_Prerequisites.2BAC8-Constraints

It was discussed in several places:
- http://answers.ros.org/question/52744/how-to-specify-dependencies-with-foo_msgs-catkin-packages/
- http://answers.ros.org/question/64448/trouble-with-catkin-compiling-node-and-generating-messages-in-same-package/
- https://groups.google.com/forum/?fromgroups#!searchin/ros-sig-buildsystem/package$20dependency/ros-sig-buildsystem/dvVO5QCHBLM/QtXUOf7EOhQJ
- https://github.com/ros/catkin/issues/547

There is no good technical solution to this issue that I am aware of for this problem other than calling `add_dependencies()` as you have done. I won't reiterate the technical discussion since it's been hashed over several times.

> I think this should not be needed (because then usage of "core" ROS message packages would be different from usage of own message packages).

It's required for technical reasons. You should do this for "core" ROS message packages as well. It "happens" to work for the common message packages because you have them installed (and therefore in a separate workspace). If you built your packages with `catkin_make_isolated` or by chaining them across workspaces then you would not run into this problem. It's always best to add the dependency though in case someone tries to build your packages with `catkin_make`.

---

I'm going to close this, but you can feel free to continue commenting and I can reopen the issue if needed.

**Closed as completed by wjwwood** 2016-05-25 18:48 UTC

**Comment by peci1** [comment] 2016-05-26 09:25
Thanks for the elaborate answer. I actually did ask on [answers.ros.org](http://answers.ros.org/question/235035/add_dependencies_generate_messages_cpp-needed-when-depending-on-own-message-package/), but nobody was able to answer the question. So I thought it is a bug.

The API docs seem to say it clearly, that you need to depend on EXPORTED_TARGETS for every target that uses ROS messages.

However, the [wiki page](http://wiki.ros.org/catkin/CMakeLists.txt#Important_Prerequisites.2BAC8-Constraints) is quite unclear on this. 

```
If you have a package which builds messages and/or services as well as executables that use them, you need to create an explicit dependency on the automatically-generated message target so that they are built in the correct order. 
```

I interpreted this so that if I don't have messages in the same package, I don't have to add the dependency. So I propose improving the docs there. What about splitting section 8 to two subsection - one for "generating messages in your package" and one for "using messages in your package"?

**Comment by wjwwood** [comment] 2016-06-21 01:15
@peci1 sorry, I dropped the ball on this. Your proposed changes seem reasonable. If you want to make the changes as you see fit and post the diff here I'll review it.

**Comment by peci1** [comment] 2016-06-21 11:43
What about changing:

`* '''If you have a package which builds messages and/or services as well as executables that use them, you need to create an explicit dependency on the automatically-generated message target so that they are built in the correct order. ('''some_target''' is the name of the target set by add_executable()):'''`

to 

`* '''If you have a package which builds messages and/or services, or builds executables that use them, or (transitively) depends on some package that uses messages and/or services, you need to create an explicit dependency on the automatically-generated message target so that they are built in the correct order. ('''some_target''' is the name of the target set by add_executable()):'''`

**Comment by wjwwood** [comment] 2016-06-21 23:45
I actually don't think the second one is correct. If you transitively depend on a message package and that package is in your workspace, then the appropriate target will be in the `catkin_EXPORTED_TARGETS` CMake variable. So the direct or indirect (transitive) dependencies which build messages are covered by depending on `catkin_EXPORTED_TARGETS`.

The snippet that comes after the paragraph you're changing, `add_dependencies(some_target ${${PROJECT_NAME}_EXPORTED_TARGETS})`, is required only if the current package is both building messages and some library or executable (called `some_target` here).

**Comment by peci1** [comment] 2016-06-22 09:24
Aha, so should I understand it like this?
- If my package doesn't build any messages, and no target (indirectly) depends on any other messages, I don't have to do anything (though I can't imagine a ROS package that wouldn't depend on any messages)
- If my package doesn't build any messages, and a target (indirectly) depends on any other messages, I need to add `add_dependencies(some_target ${catkin_EXPORTED_TARGETS})`
- If my package builds messages, and a target depends on them, I need to add `add_dependencies(some_target ${${PROJECT_NAME}_EXPORTED_TARGETS})`. Is that sufficient, or do I also have to add `add_dependencies(some_target ${catkin_EXPORTED_TARGETS})`?

I don't see a reason, why couldn't catkin add the `add_dependencies(some_target ${catkin_EXPORTED_TARGETS})` clause automatically to all defined targets. I don't think many people would granularize the dependencies to such a degree that they would add only those package-specific EXPORTED_TARGETS that are really needed for each of the defined targets.

**Comment by wjwwood** [comment] 2016-06-24 00:09
> If my package doesn't build any messages, and no target (indirectly) depends on any other messages, I don't have to do anything (though I can't imagine a ROS package that wouldn't depend on any messages)

Yes. There are quite a few packages which don't use the middleware or messages. And even within packages that do, there are plenty of ROS-agnostic libraries and tests that don't use them.

> If my package doesn't build any messages, and a target (indirectly) depends on any other messages, I need to add add_dependencies(some_target ${catkin_EXPORTED_TARGETS})

That's correct. It's always safe to add a dependency on the `catkin_EXPORTED_TARGETS` cmake variable.

> If my package builds messages, and a target depends on them, I need to add add_dependencies(some_target ${${PROJECT_NAME}_EXPORTED_TARGETS}). Is that sufficient, or do I also have to add add_dependencies(some_target ${catkin_EXPORTED_TARGETS})?

You need to have both. `catkin_EXPORTED_TARGETS` is for message targets outside of your package, but `${PROJECT_NAME}_EXPORTED_TARGETS` is for messages inside your package. You could probably only use `${PROJECT_NAME}_EXPORTED_TARGETS` if you only use your own messages, but as I said it's always safe to add a dependency on `catkin_EXPORTED_TARGETS`.

> I don't see a reason, why couldn't catkin add the add_dependencies(some_target ${catkin_EXPORTED_TARGETS}) clause automatically to all defined targets.

It's not really about granularity of control, the problem is that there is no opportunity to do so. `catkin` doesn't have a list of your targets. If there were a function like `catkin_add_executable` then it would be possible, but for better or worse one of the design goals of `catkin` was to be as similar to CMake as possible, providing as little "magic" as possible. This has turned out to be a double edged sword, as people familiar with CMake are happy about less magic, and the result is more portable, but it also means more understanding for people who aren't as familiar with CMake or use catkin exclusively with ROS.

We created `catkin_simple` in response to this: https://github.com/catkin/catkin_simple, but it has some known limitations. The next iteration of catkin, called ament, that we're testing out in ROS 2 addresses some of these problems that made it difficult to have `catkin_simple` behave correctly all the time. So hopefully this will go away in the future. But for now, there's no technical solution that allows catkin to automatically address the dependency.

**Comment by peci1** [comment] 2016-06-24 12:47
So I suggest this update to the ROS wiki page (diff is for section 8, i.e. starting with `<<Anchor(msgs_srvs_actions)>>`):

```
44c44,50
<  * '''If you have a package which builds messages and/or services as well as executables that use them, you need to create an explicit dependency on the automatically-generated message target so that they are built in the correct order. ('''some_target''' is the name of the target set by add_executable()):'''
---
>  * '''If you have a target which (even transitively) depends on some other target that needs messages/services/actions to be built, you need to add an explicit dependency on target catkin_EXPORTED_TARGETS, so that they are built in the correct order. This case applies almost always, unless your package really doesn't use any part of ROS. Unfortunately, this dependency cannot be automatically propagated. ('''some_target''' is the name of the target set by add_executable()):'''
> 
> {{{
>   add_dependencies(some_target ${catkin_EXPORTED_TARGETS})
> }}}
> 
>  * '''If you have a package which builds messages and/or services as well as executables that use these, you need to create an explicit dependency on the automatically-generated message target so that they are built in the correct order. ('''some_target''' is the name of the target set by add_executable()):'''
48a55,61
> 
>  * '''If you your package satisfies both of the above conditions, you need to add both dependencies, i.e.:'''
> 
> {{{
>   add_dependencies(some_target ${${PROJECT_NAME}_EXPORTED_TARGETS} ${catkin_EXPORTED_TARGETS})
> }}}
> 
50c63
< If your package has two messages in a directory called "msg" named "`MyMessage1.msg`" and "`MyMessage2.msg`" and these messages depend on [[std_msgs]] and [[sensor_msgs]] and a service in a directory called "srv" named "`MyService.srv`" then you will need the following in your `CMakeLists.txt`:
---
> If your package has two messages in a directory called "msg" named "`MyMessage1.msg`" and "`MyMessage2.msg`" and these messages depend on [[std_msgs]] and [[sensor_msgs]], a service in a directory called "srv" named "`MyService.srv`", defines executable message_program that uses these messages and service, and executable nonmessage_program, which uses some parts of ROS, but not the messages/service defined in this package, then you will need the following in your `CMakeLists.txt`:
74a88,95
> 
>   # define executable using MyMessage1 etc.
>   add_executable(message_program src/main.cpp)
>   add_dependencies(message_program ${${PROJECT_NAME}_EXPORTED_TARGETS} ${catkin_EXPORTED_TARGETS})
> 
>   # define executable not using any messages/services provided by this package
>   add_executable(nonmessage_program src/main.cpp)
>   add_dependencies(nonmessage_program ${catkin_EXPORTED_TARGETS})
```

**Comment by wjwwood** [comment] 2016-07-06 20:05
Other than calling the `nonmessage_program` something like `does_not_use_local_messages_program` instead, I think that looks great.

Sorry again for my delayed response and thanks for iterating with me.

**Comment by peci1** [comment] 2016-08-02 16:01
So, would this be the final one? (just applying your suggestion):

```
44c44,50
<  * '''If you have a package which builds messages and/or services as well as executables that use them, you need to create an explicit dependency on the automatically-generated message target so that they are built in the correct order. ('''some_target''' is the name of the target set by add_executable()):'''
---
>  * '''If you have a target which (even transitively) depends on some other target that needs messages/services/actions to be built, you need to add an explicit dependency on target catkin_EXPORTED_TARGETS, so that they are built in the correct order. This case applies almost always, unless your package really doesn't use any part of ROS. Unfortunately, this dependency cannot be automatically propagated. ('''some_target''' is the name of the target set by add_executable()):'''
> 
> {{{
>   add_dependencies(some_target ${catkin_EXPORTED_TARGETS})
> }}}
> 
>  * '''If you have a package which builds messages and/or services as well as executables that use these, you need to create an explicit dependency on the automatically-generated message target so that they are built in the correct order. ('''some_target''' is the name of the target set by add_executable()):'''
48a55,61
> 
>  * '''If you your package satisfies both of the above conditions, you need to add both dependencies, i.e.:'''
> 
> {{{
>   add_dependencies(some_target ${${PROJECT_NAME}_EXPORTED_TARGETS} ${catkin_EXPORTED_TARGETS})
> }}}
> 
50c63
< If your package has two messages in a directory called "msg" named "`MyMessage1.msg`" and "`MyMessage2.msg`" and these messages depend on [[std_msgs]] and [[sensor_msgs]] and a service in a directory called "srv" named "`MyService.srv`" then you will need the following in your `CMakeLists.txt`:
---
> If your package has two messages in a directory called "msg" named "`MyMessage1.msg`" and "`MyMessage2.msg`" and these messages depend on [[std_msgs]] and [[sensor_msgs]], a service in a directory called "srv" named "`MyService.srv`", defines executable message_program that uses these messages and service, and executable nonmessage_program, which uses some parts of ROS, but not the messages/service defined in this package, then you will need the following in your `CMakeLists.txt`:
74a88,95
> 
>   # define executable using MyMessage1 etc.
>   add_executable(message_program src/main.cpp)
>   add_dependencies(message_program ${${PROJECT_NAME}_EXPORTED_TARGETS} ${catkin_EXPORTED_TARGETS})
> 
>   # define executable not using any messages/services provided by this package
>   add_executable(does_not_use_local_messages_program src/main.cpp)
>   add_dependencies(does_not_use_local_messages_program ${catkin_EXPORTED_TARGETS})
```

**Comment by wjwwood** [comment] 2016-08-02 23:50
+1

**Comment by peci1** [comment] 2016-08-03 08:45
Done.
