### ISSUE TITLE
CTestTestfile.cmake contains bad path

### ISSUE THREAD

**Issue by koniarik** [ros/catkin#957] opened 2018-09-11 10:59 UTC
I would like to use CDash as CI for my project, that requires use of 'ctest -D continuous' in build folder of the package in question, for that to work I need correct CTestTestfile.cmake

However, the CTestTestfile generate by cmake contains:
```
add_test(_ctest_schpin_ompl_gtest_collision_tests
"/home/squirrel/Projects/Schpin/build/schpin-ros/schpin_ompl/catkin_generated/env_cached.sh"
"/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py"
"/home/squirrel/Projects/Schpin/build/schpin-ros/schpin_ompl/test_results/schpin_ompl/gtest-collision
_tests.xml"
"--return-code" "/home/squirrel/Projects/Schpin/build/schpin-ros/schpin_ompl/devel/lib/schpin_ompl/collision_tests
--gtest_output=xml:/home/squirrel/Projects/Schpin/build/schpin-ros/schpin_ompl/test_results/schpin_ompl/gtest-collision_tests.xml")

```

Problem is the path after '--return-code' is /home/squirrel/Projects/Schpin/build/schpin-ros/schpin_ompl/devel/lib/schpin_ompl/collision_tests rather than /home/squirrel/Projects/Schpin/devel/lib/schpin_ompl/collision_tests ...

I tried to go through the source code, the 'add_test()' command is used here:
https://github.com/ros/catkin/blob/928c2025206e1a3f0d9d504ef5b26efe1cc95d8b/cmake/test/tests.cmake#L126-L127

The problematic path is in variable _testing_COMMAND, which is input for the function. The value itself is generated here in this case: 
https://github.com/ros/catkin/blob/b1622e2042b8fa01df2896ea12d375acf6443beb/cmake/test/gtest.cmake#L87-L89

I suppose "${_target_path}/${target}" is to blame, but I don't know where to look more for potential problems ... Could somebody look into this? Thanks a lot!

**Comment by dirk-thomas** [comment] 2018-09-11 16:05
I built the `test_roscpp` package with `catkin_make_isolated` and a following invocation of `ctest -D Continuous` works just fine. The `cmd` for one of the tests correctly references the executable in the `devel` space: e.g. `<ws>/devel_isolated/test_roscpp/lib/test_roscpp/test_roscpp-test_version`.

Please provide more information about your package as well as process / a reproducible example of your problem.

**Comment by koniarik** [comment] 2018-09-18 11:00
Tried to compile my packages with '_isolated', same problem. Tried to compile the test_roscpp package and the paths are completely different '"--return-code" "/opt/ros/melodic/share/rostest/cmake/../../../bin/rostest'.

I will try to update my project to phase when everything is taken care of so it can be easily compiled by others? It's my custom code and it's in "devel" phase. I think that may be the best course of action.

Setup:
ROS Melodic on archlinux

**Comment by dirk-thomas** [comment] 2019-03-12 19:53
I will go ahead and close this for now since there is not enough information indicating that this is a problem in this package. Please feel free to comment on the closed ticket with more information and it can be reopened if necessary.

**Closed as completed by dirk-thomas** 2019-03-12 19:53 UTC
Labels: more-information-needed
