### ISSUE TITLE
Specifying CMake options for external CMake project

### ISSUE THREAD

**Issue by wxmerkt** [ros/catkin#1007] opened 2019-04-30 17:31 UTC
Hi!
I'd like to use the following to wrap a CMake-native project in a catkin environment:
```xml
<buildtool_depend>cmake</buildtool_depend>
<export>
  <build_type>cmake</build_type>
</export>
```

While this works great to build, it defaults all options as in the CMake project. In many cases, we'd like to set a few of those - e.g., not to build tests etc. (what we would usually do by `cmake .. -DBUILD_TESTS=OFF`). Is there a way to do this, or a convenient work-around?

Thanks,
Wolfgang

**Comment by dirk-thomas** [comment] 2019-04-30 17:36
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.

**Closed as completed by dirk-thomas** 2019-04-30 17:36 UTC
Labels: question

**Comment by wxmerkt** [comment] 2019-04-30 17:50
Related answers.ros.org post: https://answers.ros.org/question/322231/specifying-cmake-options-for-external-cmake-project/

After extensive search on GitHub and reading the code prior to posting, I think this may amount to a _feature request_ beyond a question.

**Comment by Levi-Armstrong** [comment] 2019-07-01 16:02
It looks like the issue is per cmake [documentation](https://cmake.org/cmake/help/v3.13/manual/cmake.1.html) that option must be before the path to the source and from what I can tell catkin passes all arguments after providing source path. I assume they would need to add a `--cmake-options` and insert these before the source path so things are configured properly.
