### ISSUE TITLE
Catkin installs setup files incorrectly

### ISSUE THREAD

**Issue by nkoenig** [ros/catkin#515] opened 2013-09-24 18:14 UTC
My previous issue #514  was closed without giving me a chance to respond. 

I'm repeating it here. Hopefully this issue won't be closed needlessly.

Running `cmake ../; make; make install` installs setup files (setup.bash, setup.sh, setup.zsh, etc) in CMAKE_INSTALL_PREFIX. No files should ever be put directly in the CMAKE_INSTALL_PREFIX. Yet, catkin does this. 

For example, a default source build of [sandia-hand](https://bitbucket.org/osrf/sandia-hand) will put garbage in `/usr`.

**Comment by dirk-thomas** [comment] 2013-09-25 20:17
Please do not open a new ticket but comment on the existing one in the future. Issues can easily be reopened based on comments.

catkin requires a certain set of environment variables to be set. This is done via the setup.\* files so that the user does not have to set those manually. This environment can even be extended by environment hooks provided by any package. Currently these files are being installed into the CMAKE_INSTALL_PREFIX.

Arguably when the install prefix is set to `/usr` that location is not great but ROS does currently not cleanly support to install packages to `/usr` (see #380).

Would you consider your ticket to be a duplicate of #380 or what else would you propose with the setup files to happen?

**Comment by nkoenig** [comment] 2013-09-25 22:15
Thanks for the response. This looks like this is a duplicate of issue #380.

**Comment by dirk-thomas** [comment] 2013-09-25 22:35
I marked it as _duplicate_ and will close the ticket.

**Closed as completed by dirk-thomas** 2013-09-25 22:35 UTC
Labels: duplicate
