### ISSUE TITLE
catkin_make does not check dependencies

### ISSUE THREAD

**Issue by ahendrix** [ros/catkin#466] opened 2013-07-10 20:39 UTC
When I run catkin_make on a system with missing dependencies, it often fails at some point during the cmake generation process with an obscure error, usually being unable to find a cmake config for the missing dependency. This is difficult to debug.

Catkin should check that all build dependencies are present before invoking cmake. This will catch missing dependencies and typos in the dependencies.

**Comment by dirk-thomas** [comment] 2013-07-10 20:55
How would you suggest that should be done?

**Comment by ahendrix** [comment] 2013-07-10 21:16
While catkin traverses the package.xml files, it should collect package names and dependencies, and then try to resolve all of those dependencies, first from the installed packages, and then using rosdep.

**Comment by wjwwood** [comment] 2013-07-10 21:17
I think what @dirk-thomas meant to say is, that when you invoke "catkin" via `cmake` there is no opportunity to do this.

You _could_ have the `catkin_make` script check this, but it would be really slow, because you have to ask `rosdep` about each entry. You can essentially do this check like this:

``` bash
cd /path/to/catkin_ws
rosdep install --from-paths src --ignore-src --rosdistro groovy -y --simulate
```

That command will try to install any missing dependencies (catkin or otherwise), but it will consider packages in your `ROS_PACKAGE_PATH` "resolved" and not try to install them.

The problem is that this takes a very long time, so it's not something you want to do each time you invoke `catkin_make`.

Another point is that often you don't know the ROS Distro at the time when you invoke `catkin_make`, see that you have to pass it to `rosdep` in the above example, so you would have to tell `catkin_make` about that too. For example, if some package in your workspace depends on `pcl_conversions`, then the ROS distro is required to resolve that, because it does not exist in groovy but it does in hydro.

**Comment by dirk-thomas** [comment] 2013-07-12 21:56
I will mark this as _wontfix_ since I don't see a way to perform this check beyond what it currently does with native CMake find_package().

**Closed as completed by dirk-thomas** 2013-07-12 21:56 UTC
Labels: wontfix
