### ISSUE TITLE
catkin should handle different `etc` folder layouts

### ISSUE THREAD

**Issue by wjwwood** [ros/catkin#396] opened 2013-03-18 17:25 UTC
Currently, the `etc` folder is assumed to be inside the installation prefix, e.g. `/opt/ros/groovy/etc` for `/opt/ros/groovy`. This is incorrect for the `/usr` path, which expects `/etc` to be used.

See:

https://groups.google.com/forum/?fromgroups=#!searchin/ros-sig-buildsystem/etc/ros-sig-buildsystem/eVaiQ4Annu4/ekNaasxxYo0J

This is a problem for packaging catkin packages as `/usr` prefixed binaries. There are other locations where this is possible a problem, like rospkg.

@dirk-thomas if you still have the searches up can you reference the affect packages that we know about?

**Comment by dirk-thomas** [comment] 2013-03-18 17:50
The following items are affected by that (not sure if that is a complete list) and will likely need to be updated to support that use case:
- [ ] [REP 123](https://github.com/ros-infrastructure/rep/blob/master/rep-0123.rst) environment variable ROS_ETC_DIR
- [ ] catkin_pkg: `get_global_etc_destination()` and `get_package_etc_destination()`
- [ ] catkin: `etc` destination variables, `catkin_find` with --etc
- [ ] genmsg message generators location
- [ ] rospkg: `get_etc_ros_dir()`
- [ ] rosgraph: python_logging.conf
- [ ] roslaunch: roscore.xml

**Comment by jack-oquin** [comment] 2013-03-18 19:10
There is also a [REP-0122](http://www.debian.org/doc/debian-policy/ch-docs.html) update required. I volunteer for that, once we decide to proceed with this change.

**Comment by jack-oquin** [comment] 2013-03-18 19:16
Another option is to move most of **${PREFIX}/etc** to **${PREFIX}/share/ros/etc**. Then **$ROS_ETC_DIR** could point there. There should _not_ be a **share/langs** directory. That name is too vague to ever be exposed at the **/usr/share** level. 

I still prefer moving **etc/catkin** to **share/catkin**, keeping it somewhat separate from ROS.

**Comment by dirk-thomas** [comment] 2013-03-18 19:25
The major problem with ROS_ETC_DIR is that it is does not work with overlays by design. Pointing to a single folder will not work anyway.

**Comment by jack-oquin** [comment] 2013-04-03 19:35
I wonder if it is now too late in Hydro for this change. Should it wait until Indigo?

If it is still in Hydro, I need to do the REP-0122 update right away.

**Comment by dirk-thomas** [comment] 2013-04-04 09:06
First there need to be a clear concept / plan how all of the pending questions should be handled which everybody agrees on. And then someone would need  to realize them.
Currently the issue is marked as "untargeted" since nobody is actively working on it and it is not scheduled to be realized for a specific milestone.

**Comment by jack-oquin** [comment] 2013-04-04 12:40
Doesn't that mean it's not happening for Hydro?

I don't see any harm with scheduling it for Indigo. We all have other things to do. It does not matter much as long as we are only releasing to /opt/ros and have no immediate plans for making actual Ubuntu packages.

The main thing is not to write more tools that depend on $PREFIX/etc and will have to be fixed later.

**Comment by tfoote** [comment] 2013-04-04 18:03
Most likely yes it will not make it into Hydro.  When we kick off Indigo
development we should review all untargeted tickets for targeting into
Indigo.

**Comment by dirk-thomas** [comment] 2019-08-12 18:06
Closing due to inactivity.

**Closed as completed by dirk-thomas** 2019-08-12 18:06 UTC
Labels: enhancement
