### ISSUE TITLE
<built_type> doesn't work anymore with multiple tags

### ISSUE THREAD

**Issue by facontidavide** [ros/catkin#1173] opened 2022-05-21 19:21 UTC
This doesn't work anymore:
```xml
  <export>
      <build_type condition="$ROS_VERSION == 2">ament_cmake</build_type>
      <build_type condition="$ROS_VERSION == 1">catkin</build_type>
  </export>
```
If I run `echo $ROS_VERSION` I can see either 1 or 2

Error message:

```
Repository type: git
Found packages: behaviortree_cpp_v3
Traceback (most recent call last):
  File "/usr/bin/catkin_prepare_release", line 33, in <module>
    sys.exit(load_entry_point('catkin-pkg==0.5.0', 'console_scripts', 'catkin_prepare_release')())
  File "/usr/lib/python3/dist-packages/catkin_pkg/cli/prepare_release.py", line 217, in main
    _main()
  File "/usr/lib/python3/dist-packages/catkin_pkg/cli/prepare_release.py", line 272, in _main
    build_type = package.get_build_type()
  File "/usr/lib/python3/dist-packages/catkin_pkg/package.py", line 167, in get_build_type
    raise InvalidPackage('Only one <build_type> element is permitted.', self.filename)
catkin_pkg.package.InvalidPackage: Error(s) in package '././package.xml':
Only one <build_type> element is permitted.

```

**Comment by Rayman** [comment] 2022-05-23 15:53
Is this the same error as https://github.com/ros/catkin/issues/1170?

**Comment by gbiggs** [comment] 2022-05-24 00:33
Duplicate of #1170

**Closed as completed by gbiggs** 2022-05-24 00:33 UTC

**Comment by ivanpauno** [comment] 2022-06-23 20:49
I think that this and #1170 are different, but IIUC the issue reported here was solved in https://github.com/ros-infrastructure/catkin_pkg/issues/336.
