### ISSUE TITLE
catkin_generate_changelog adds unicode contributor names, causes bloom-release to fail

### ISSUE THREAD

**Issue by mikeferguson** [ros/catkin#587] opened 2014-02-03 20:40 UTC
catkin_generate_changelog does not clean the names of contributors, and thus bloom-release later fails if you didn't catch that a particular contributor's name contains unicode. The error message from bloom-release also doesn't really tell you where the unicode came in, making it quite difficult to track down.

I presume adding  unicode support to bloom-release is probably nastier than simply removing the unicode in the generate changelog script, and that is why I have filed this bug report here.

**Comment by tfoote** [comment] 2014-02-03 21:04
What version of bloom are you using? I think this was patched https://github.com/ros-infrastructure/bloom/pull/210

**Comment by mikeferguson** [comment] 2014-02-03 21:07
First try was with 0.4.7, I got warnings about a new release, I updated to 0.4.8-1 but it still crashed the same way. My traceback looks a bit different:

```
Traceback (most recent call last):
  File "/usr/bin/git-bloom-generate", line 9, in <module>
    load_entry_point('bloom==0.4.7', 'console_scripts', 'git-bloom-generate')()
  File "/usr/lib/pymodules/python2.7/bloom/commands/git/generate.py", line 247, in main
    run_generator(generator, args)
  File "/usr/lib/pymodules/python2.7/bloom/commands/git/generate.py", line 162, in run_generator
    gen.post_rebase, destination)
  File "/usr/lib/pymodules/python2.7/bloom/commands/git/generate.py", line 101, in try_execute
    retcode = func(*args, **kwargs)
  File "/usr/lib/pymodules/python2.7/bloom/generators/debian/generator.py", line 505, in post_rebase
    data = self.generate_debian(package, distro)
  File "/usr/lib/pymodules/python2.7/bloom/generators/debian/generator.py", line 632, in generate_debian
    template_files = process_template_files('.', subs)
  File "/usr/lib/pymodules/python2.7/bloom/generators/debian/generator.py", line 344, in process_template_files
    return __process_template_folder(debian_dir, subs)
  File "/usr/lib/pymodules/python2.7/bloom/generators/debian/generator.py", line 328, in __process_template_folder
    result = em.expand(template, **subs)
  File "/usr/lib/pymodules/python2.7/em.py", line 3016, in expand
    result = interpreter.expand(_data, _locals)
  File "/usr/lib/pymodules/python2.7/em.py", line 2209, in expand
    self.string(data, '<expand>', locals)
  File "/usr/lib/pymodules/python2.7/em.py", line 2368, in string
    self.safe(scanner, True, locals)
  File "/usr/lib/pymodules/python2.7/em.py", line 2378, in safe
    self.parse(scanner, locals)
  File "/usr/lib/pymodules/python2.7/em.py", line 2398, in parse
    token.run(self, locals)
  File "/usr/lib/pymodules/python2.7/em.py", line 1535, in run
    self.subrun(info[0][1], interpreter, locals)
  File "/usr/lib/pymodules/python2.7/em.py", line 1621, in subrun
    token.run(interpreter, locals)
  File "/usr/lib/pymodules/python2.7/em.py", line 1335, in run
    interpreter.write(str(result))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 51: ordinal not in range(128)
```

**Comment by wjwwood** [comment] 2014-02-03 21:07
https://github.com/ros-infrastructure/bloom/pull/210 should be in `bloom` 0.4.5+, though there may still be lingering errors with `empy` (the templating library we use) not supporting unicode correctly. Can you provide the bloom log, it will be located in `~/.bloom_logs`.

**Comment by wjwwood** [comment] 2014-02-03 21:09
Yeah, that is a bug in `empy`, I think our hands are tied as the version of `empy` in debian will not likely change anytime soon. You might be able to get `empy` from `pip`.

**Comment by mikeferguson** [comment] 2014-02-03 21:10
https://gist.github.com/mikeferguson/f0768c2d4df4a3bd8cdf is the full log

**Comment by wjwwood** [comment] 2014-02-03 21:16
This is the relevant bloom issue: https://github.com/ros-infrastructure/bloom/issues/196

I am going to close this one as a duplicate of that one.

**Closed as completed by wjwwood** 2014-02-03 21:16 UTC

**Comment by mikeferguson** [comment] 2014-02-03 21:20
Thanks for the feedback, I'll try out getting a new empy later.
