### ISSUE TITLE
Catkin configure time does not scale

### ISSUE THREAD

**Issue by ahundt** [ros/catkin#605] opened 2014-03-06 04:10 UTC
As the number of packages utilized grows, the configuration time grows at an excessive rate. Once the number of packages reaches 140, the configure time can exceed 5 minutes. It actually appears to grow exponentially. 

I have worked on a utility similar to Catkin that provides a solid point of comparison called CMake BASIS. https://github.com/schuhschuh/cmake-basis

Here is a chart showing the absolute configuration time on a **logarithmic scale** :
![catkin performance comparison 001](https://f.cloud.github.com/assets/55744/2341812/2c1851ba-a4e4-11e3-969d-418421b76555.png)

Here is a chart showing a comparison of configure time vs a hard coded pure CMake build on a linear scale:
![catkin performance comparison 002](https://f.cloud.github.com/assets/55744/2341832/70209c5a-a4e4-11e3-8248-9d39c740f7b9.png)

As you can see from these tests, the configuration time of Catkin is an order of magnitude slower than it should be. Hopefully this data will be helpful for prioritizing and evaluating this problem.

**Comment by wjwwood** [comment] 2014-03-06 05:30
Interesting results. I would like to understand why catkin appears to be slower in this context, but I have some questions about your results.
- How did you perform these tests?
- What packages did you use?
- Did you use the same packages for each of the systems?
- Can I reproduce these results some how?
- Did you use a single CMake invocation on a pure catkin workspace (catkin_make) or did you use catkin_make_isolated?
- How did you setup the "Pure CMake" system (using `add_subdirectory` or invoking cmake on each "package" separately and adding the times)?
- How does BASIS build multiple packages at once? How is it different from what catkin does?

The graphs are pretty, but unfortunately this doesn't give me a lot of information.

**Comment by ahundt** [comment] 2014-03-06 05:59
I'll give you the info I can, sorry much of it has to be vague and meta-info but I don't have permission to release actual source code.

> Interesting results. I would like to understand why catkin appears to be slower in this context, but I have some questions about your results.
> 
> How did you perform these tests?

Catkin:
Used an existing project build system with 140 packages for a project + catkin_make

BASIS:
Set up 12 packages with the CMakeLists.txt files ported to no longer use python or catkin calls except for ros_messages, then specified the dependencies in the same way Catkin would in the BasisProject.cmake file. For this one I extrapolated from 12 to 140.

CMake:
Did the same thing as basis, except simply called `add_subdirectory()` in the topologically correct order. For this one all 140 packages were completely reimplemented.

> What packages did you use?

Don't have this offhand, and I can't provide all of them if I did, but I can give a basic summary. 

Many of them were custom implemented packages, but none of them were particularly special or unusual, all were implemented as the Catkin tutorials specify and used the normal depends.xml and built 1-10 libraries/binaries, and typically 0-5 ros messages. 

> Did you use the same packages for each of the systems?

Yes

> Can I reproduce these results some how?

Catkin: The best way to reproduce the slowness is to build that number of ros packages from source. The dependency solver is probably rerun for each package, causing the performance problems. With 140 packages more than 1 second configure per package is too slow.

BASIS/CMake:
- the cmake functions to generate ROS messages must be modified to remove some of their dependencies on Catkin.
- Catkin must also be modified to eliminate some hard coded values so that only find_package(catkin) needs to be called so that the ros message creation calls work. 
- Each ros package must be manually ported to eliminate any catkin specific calls that aren't for ros messages.

Pure CMake:
- A toplevel CMake script needs to be created that calls add_subdirectory in a topologically correct order and makes the appropriate find_package calls.
- run normal cmake and make steps

BASIS:
- run `basisproject create` to generate scripts (see http://opensource.andreasschuh.com/cmake-basis/quickstart.html)
- copy the appropriate CMake scripts into the package
- modify BasisProject.cmake to include the same module dependencies that were in the Catkin dependency XML file.
- run normal cmake and make steps

I've contacted the author of the Catkin tweaks I used to see if I can get a patch. 

> Did you use a single CMake invocation on a pure catkin workspace (catkin_make) or did you use catkin_make_isolated?

catkin_make

> How did you setup the "Pure CMake" system (using add_subdirectory or invoking cmake on each "package" separately and adding the times)?

add_subdirectory

> How does BASIS build multiple packages at once? How is it different from what catkin does?

Conceptually it is basically identical to Catkin. However, all configure steps are 100% implemented in the CMake language. It will topologically sort the modules according to their dependencies, then call add_subdirectory in that order. It also has some additional functionality beyond what catkin provides, but that's not relevant to the issue.

Some possible sources of the huge performance gap:
- BASIS doesn't have to switch between python and CMake all the time
- The catkin topological sort and dependency resolution is either rerun over and over or extremely slow. 

> The graphs are pretty, but unfortunately this doesn't give me a lot of information.

Hopefully my answers to your questions will be helpful.

**Comment by wjwwood** [comment] 2014-03-06 06:35
> For this one I extrapolated from 12 to 140.

You mean you extrapolated to estimate the time BASIS would take or you extrapolated the packages you used (repeated them or something)?

> ... and used the normal depends.xml and ...

I guess you mean `package.xml`?

> However, all configure steps are 100% implemented in the CMake language.

That sounds awful :smile:, but definitely faster. We chose to use Python for some of the functions (topological sorting) for two reasons:
1. Our sanity
2. Reuse outside of the build system

> Some possible sources of the huge performance gap:
> - BASIS doesn't have to switch between python and CMake all the time
> - The catkin topological sort and dependency resolution is either rerun over and over or extremely slow

Ok, it may be the case that switching back and forth between Python and CMake would make it linearly slower, but it seems unlikely that this is the reason for the exponential increase you are seeing (unless the number of calls to Python is proportional to the number of dependencies).

Conceptually I don't know of any reason for the the topological ordering to be done for each package (in the catkin_make case), but it may be that we must do this for sorting of include directories or something like that. The performance may also be related to the use of the develspace.

@dirk-thomas would likely have more insight into this.

The performance of the catkin configuration step should be investigated, but in my opinion the cost incurred for very large builds should be infrequent. Our recommendation is to build the bulk of your packages once, and then make a new catkin workspace containing only the packages you are currently iterating on. In my experience you are rarely touching large numbers of packages simultaneously, so placing a smaller workspace on top is always going to be more efficient than running the configuration of all of your packages each time you make a change.

> Hopefully my answers to your questions will be helpful.

These answers were much more helpful, thanks.

**Comment by ahundt** [comment] 2014-03-06 16:53
> You mean you extrapolated to estimate the time BASIS would take or you extrapolated the packages you used (repeated them or something)?

Extrapolated the time BASIS would take, the pure cmake and the catkin versions were tested with all 140 packages.

> > However, all configure steps are 100% implemented in the CMake language.
> > That sounds awful , but definitely faster.

I would say that's accurate. :+1: 

> I guess you mean package.xml?

yeah

> The performance of the catkin configuration step should be investigated, but in my opinion the cost incurred for very large builds should be infrequent. Our recommendation is to build the bulk of your packages once, and then make a new catkin workspace containing only the packages you are currently iterating on.

We considered this but it hasn't proven practical. That would mean each of our developers (~30) has to know all of the details of ROS to set up their own tree. Some only work briefly on the project so that is definitely not the case. Also, if someone is working on a package that tons of others depend on, the potential benefits are also lost. 

Unfortunately, Our solution ended up being to take catkin out, which is how I was able to create the chart. This meant only 1-2 experts had to work on the change, and it sped up configure time from 5+ minutes to <30 seconds. Obviously ROS needs to do the dependency resolution so your best case will probably be closer to BASIS performance. 

You may want to consider taking the [CMake topological sort implementation](https://github.com/schuhschuh/cmake-basis/blob/3adece1f535928c96bd722fdf8a489863f93a304/src/cmake/TopologicalSort.cmake), and perhaps any other code you may find useful. The license is BSD so there shouldn't be a problem. I would think it even better if you considered utilizing BASIS since it does offer some neat stuff that would be useful to ROS, but of course that isn't reasonable to expect. :-)

Otherwise if there is any more info I can provide to help diagnose the issue and speed up catkin I'd be happy to help.

**Comment by dirk-thomas** [comment] 2014-03-06 16:56
We are building complete ROS distributions frequently in a single workspace (with several hundred packages) and have never experienced anything like "exponential configure time". So I would be a little bit surprised if that would be very different for any different set of packages.

I am certain that catkin is slower than other solutions - especially when they are pure CMake and not utilizing external programs. But on the other hand your comparison mentions that in order to build similar stuff with pure CMake or BASIC that you stripped out a lot of catkin functionality. Obviously the performance will become better when removing steps from the configure phase. I am certain that would be the case for any domain and programming language.

We would be more than happy to look into potential performance issues and improve the configure time with catkin if possible, But in order to do so we either need a ready-to-run example workspace or an exact command sequence which reproduces an exponential configure time.

Please consider to provide those necessary information in order to enable further investigations.

**Comment by ahundt** [comment] 2014-03-06 16:57
> But on the other hand your comparison mentions that in order to build similar stuff with pure CMake or BASIC that you stripped out a lot of catkin functionality. 

In the case of BASIS I stripped out Catkin functionality to replace it with the corresponding BASIS functionality. The net effect was that very little or none was lost, and some other functionality was added. The overlap is very high but I can't guarantee there is some simple function in one that isn't in the other.

**Comment by dirk-thomas** [comment] 2014-03-06 17:01
The performance of the topological sort is neglectable since it is a one-time cost in the beginning of the configure step and takes never more than a few seconds. While calling Python for that algorithm implies additional costs (a fraction of a second) it can not be responsible for an exponential runtime growth as you describe it.

**Comment by ahundt** [comment] 2014-03-06 17:10
> The performance of the topological sort is neglectable since it is a one-time cost in the beginning of the configure step and takes never more than a few seconds. While calling Python for that algorithm implies additional costs (a fraction of a second) it can not be responsible for an exponential runtime growth as you describe it.

You are probably right, I was merely speculating on the source of the problem. 

> We would be more than happy to look into potential performance issues and improve the configure time with catkin if possible, But in order to do so we either need a ready-to-run example workspace or an exact command sequence which reproduces an exponential configure time.

I'll see what additional info I can get to you, but I figured a vague report would be better than none at all.

**Comment by tfoote** [comment] 2014-03-06 20:07
A vague report is useful. However it's hard to reconcile your report with our experience. 

As a spot check I checked out all 187 catkin packages in the desktop variant and it configures in 63 seconds on my desktop. Which is very different from your chart suggesting that should take hundreds of seconds. 

How to reproduce below. with full console output: https://gist.github.com/tfoote/329af04fb21675d4283b

```
rosinstall_generator desktop --rosdistro hydro --deps --tar --catkin-only > hydro-desktop-wet.rosinstall
wstool init src hydro-desktop-wet.rosinstall -j8
time ./src/catkin/bin/catkin_make foo
...
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/desktop/build
####
#### Running command: "make foo -j8 -l8" in "/tmp/desktop/build"
####
make: *** No rule to make target `foo'.  Stop.
Invoking "make" failed

real    1m3.297s
user    0m49.679s
sys 0m10.045s
```

**Comment by ahundt** [comment] 2014-03-17 19:50
A fellow developer also mentioned the following:

> It is hard to say [why the disparity exists]. I got similar results for running catkin_make on
> the base ROS packages. That set of packages and ours are not
> really comparable though. A lot of their packages are just scripts
> or python code which are basically no-ops for the cmake configure.
> Also the dependency graph of the base ROS build is much simpler
> than our repository.

**Comment by dirk-thomas** [comment] 2014-04-04 17:17
Please consider providing e.g. a list of command sequences, a rosinstall file, or something similar which makes it possible to reproducible the issue.

Otherwise I will have to close this ticket simple because our tests did not show any similar performance issues and there is not enough information to perform any further investigation on this.

**Comment by ahundt** [comment] 2014-04-04 17:52
Create a test case where there are 20 packages each with 20 real dependencies where an actual find or config script needs to be run, and I believe you will start to see the slowdown occur. I'm sorry I can't give you more but our real code is proprietary so I can't get permission to release it.

I did try to get permission to release what we could, specifically our generate_messages() enhancement as referenced above, and I supplied links to CMake only solvers which would also improve the situation, but part of the core of the problem is the python/CMake switching.

Perhaps an alternative solution would be to figure out how to keep python running in the background over the whole configure time so that the startup/shutdown cost is lower if python is completely necessary, though personally CMake only implementations aren't fun to write, but they aren't that bad either. 

The key here to reproduce the problem is create a synthetic test with large numbers of dependencies plus repeated calls between python and CMake, that's what triggers the problem.

**Comment by wjwwood** [comment] 2014-04-04 18:02
Unfortunately, we don't have time to construct a workspace which may or may not expose the behavior you're talking about. If, in the future, you can provide a subset of your system (even in private channels) which we can test against and reproduce the behavior, then we will look into it. Until then I would say that we will have take no action, but perhaps your description of the problem will allow someone else to look into the issue in the future.

**Comment by ahundt** [comment] 2014-04-04 18:11
I agree, this is an unfortunate barrier. Earlier someone mentioned that they checked out all 187 catkin repositories. What about simply, for a quick test, peppering some extra fake dependencies on other catkin repositories throughout? 

That would probably only take a short time to test, especially if you could use a nice little 1 liner sed script or something to add fake dependencies to all 187 packages.

**Comment by dirk-thomas** [comment] 2014-04-05 01:31
@ahundt That sounds like a feasible way. Please go ahead and put together all these commands and measure the configure time you get before and after extending the dependencies. If there is a significant increase please share your command sequence so that we can reproduce and look into it.

**Comment by Yeraze** [comment] 2014-04-23 15:18
Has there been any progress on this?

I have a project using Catkin (just for a piece of it, not all) and a `make -j4` when I change _nothing_ takes over 2 minutes just to realize nothing has changed..  Prior to integrating catkin (Raw CMake) it took about 5 seconds.

**Comment by dirk-thomas** [comment] 2014-04-23 16:21
As mentioned before on this ticket: someone needs to provide a ready-to-user example which demonstrated the issue since we do _not_ have the problem for normal workspace (e.g. when building hydro desktop). Without any such input there will be no action from the maintainers.

**Comment by Yeraze** [comment] 2014-04-23 16:24
Well, when building the Hydro desktop how long does it take to run a 2nd `make`, when nothing has changed?

**Comment by dirk-thomas** [comment] 2014-04-23 16:31
No time.

**Comment by Yeraze** [comment] 2014-04-23 16:36
ok.. This might be part of the problem..

In our system we have dozens of submodules.. so we have a toplevel Makefile that goes through them and builds them all separately.. For the catkin stuff, it reruns `cmake` and then does `make`.  For most projects, the CMake step is screaming fast because all the data is already cached in the `CMakeCache.txt` file, but for the Catkin stuff it seems to recrawl the entire dependency stack, hence the two minutes.

So I guess the real question is not make, But how long does it take to re-run cmake after a first successful config is generated.

**Comment by dirk-thomas** [comment] 2014-04-23 17:00
Again: please consider to provide a reproducible example, a sequence of commands which demonstrate the problem for you.

**Comment by Yeraze** [comment] 2014-04-23 17:04
I would love to, but a) my code is unfortunately not sharable and b) I don' t understand catkin well enough to create an example.

The particularly offending component is ROS compiled like so:

```

        @source $(CATKIN_PARENT_ENV) \
          && catkin_make_isolated \
               --source=$(src) \
               --build=$(BUILD_DIR) \
               --devel=$(INSTALL_DIR) \
               --merge \
               --only-pkg-with-deps \
                 camera1394 \
                 common_msgs \
                 cv_bridge \
                 dynamic_reconfigure \
                 eigen_conversions \
                 image_common \
                 image_view \
                 interactive_markers \
                 ros_comm \
                 roscpp_core \
                 rosdoc_lite \
                 rqt_plot \
                 rqt_reconfigure \
                 rviz \
               --cmake-args -DBUILD_SHARED_LIBS=ON \
                            -DCMAKE_MODULE_PATH="$(CMAKE_MODULE_PATH)" \
                            -DCMAKE_CXX_FLAGS="-I$(YAML_INSTALL_DIR)/include -L$(YAML_INSTALL_DIR)/lib" \
                            -DCMAKE_SHARED_LINKER_FLAGS="-Wl,-rpath $(YAML_INSTALL_DIR)/lib"
```

Like I said, once cmake has run successfully once and build everything, subsequent executions of this command take 2+ minutes when nothing has changed.

**Comment by dirk-thomas** [comment] 2014-04-23 17:20
I tried a workspace containing all repos which are part of the `ros_base` metapackage in _Indigo_. These are 87 packages without catkin and console_bridge (which are build separately since the later one is a plain cmake package).

Repeated invocation of `catkin_make` takes less then 10s for me only which is checking that all make targets are actually up-to-date. It does _not_ invoke CMake again but implicitly runs the make target `cmake_check_build_system` which checks if CMake needs to be run again.

For `catkin_make_isolated` the time is about 30s which is less then half a second per package. As in the previous case no CMake is invoked but only the make targets are checked that they are up-to-date.

If you want your scenario to be debugged please either look into it yourself or provide enough information to make reproducing the case as easy as possible (aka by preparing a command sequence which others can run without any effort).

**Comment by wjwwood** [comment] 2014-04-23 18:44
@Yeraze you are using `catkin_make_isolated` which means that each catkin package has to have `make cmake_check_build_system` and `make` called on them, in topological order.

If you did not touch any of the packages being passed to `catkin_make_isolated` then you shouldn't run `catkin_make_isolated`.

If you want one invocation of `cmake`, and therefore a much faster non-operation configure call, then you should use `catkin_make`, or just `cmake` (you can treat a catkin workspace as a `cmake` project).

If you are using `catkin_make_isolated` then what you are seeing and what @ahundt reported here aren't really comparable as the build process is completely different and the time it takes to build each is affected by different factors.

**Comment by dirk-thomas** [comment] 2014-10-21 21:47
I will close this ticket for now since there is no further information provided indicating what exactly to address. Please feel free to comment with more information to reopen the ticket.

**Closed as completed by dirk-thomas** 2014-10-21 21:47 UTC

**Comment by alexiswintersamp** [comment] 2022-02-24 21:25
Just wanted to add here that the graph shown originally doesn't seem to show exponential growth I don't think. I think the poster might have forgot that both axes were on a log scale. But if you look at the data points for catkin they are:

1 package: 2-3 secs
12 packages: 30 secs
140 packages: 300 secs

These look linear to me. It's just that it seems catkin is adding a lot of overhead per package.
