### ISSUE TITLE
catkin_make_isolated does not produce setup.bash etc.

### ISSUE THREAD

**Issue by piyushk** [ros/catkin#339] opened 2013-01-30 01:31 UTC
The [rosbuild + catkin workspace tutorial](http://www.ros.org/wiki/catkin/Tutorials/using_rosbuild_with_catkin) does not work if you are using catkin_make_isolated instead of catkin_make.

No setup.bash (etc.) files are produced in devel_isolated that can be used as the setup-file for the rosbuild workspace (or source directly from bashrc for that matter)

**Comment by piyushk** [comment] 2013-01-30 01:35
Here's the answers.ros thread for a bit more context: http://answers.ros.org/question/52756/issues-creating-a-rosbuild-overlay-on-top-of-catkin-packages/

**Comment by tkruse** [comment] 2013-01-30 10:23
I think this is a duplicate of #327

**Closed as completed** 2013-02-04 21:24 UTC
Labels: duplicate

**Comment by tkruse** [comment] 2013-02-04 21:31
Actually I think this is a valid issue, the isolated devel space could really produce a .rosinstall file

```
- setup-file:
     local-name: /path/to/devel_isolated/setup.sh
```

Then a rosbuild overlay should be possible I think.

**Comment by tkruse** [comment] 2013-02-05 20:33
Reopen and assign to William, please.
