### ISSUE TITLE
Search for 'catkin' in workspace failed

### ISSUE THREAD

**Issue by zhangyongwei93** [ros/catkin#866] opened 2017-04-27 10:20 UTC
When I run `catkin_make` in a ros workspace, it output:

> CMake Error at CMakeLists.txt:20 (message):
  Search for 'catkin' in workspace failed (catkin_find_pkg catkin
  /home/ubuntu/workspace/05.usb_cam_calibrate/src): Traceback (most recent
  call last):
    File "/usr/bin/catkin_find_pkg", line 5, in <module>
      from pkg_resources import load_entry_point
    File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 72, in <module>
      import packaging.requirements
    File "/usr/local/lib/python2.7/dist-packages/packaging/requirements.py", line 59, in <module>
      MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
  TypeError: __call__() takes exactly 2 arguments (1 given)
-- Configuring incomplete, errors occurred!
See also "/home/ubuntu/workspace/05.usb_cam_calibrate/build/CMakeFiles/CMakeOutput.log".

I have install catkin by `sudo apt-get install ros-jade-catkin`, but the problem is not resolved.

**Comment by dirk-thomas** [comment] 2017-04-27 17:00
I doesn't look like the problem is related to `catkin`. Please ask your question on http://answers.ros.org instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.

**Closed as completed by dirk-thomas** 2017-04-27 17:00 UTC

**Comment by sherlei** [comment] 2021-12-21 08:54
https://blog.csdn.net/weixin_42696356/article/details/90814578
maybe you can refer to this, it fixed my problem that kinetic use python 3.5 when system python is set to python2.7.
